### ISSUE TITLE
Installation du cluster Elasticsearch

### ISSUE THREAD

**Issue by pdhoulle** [pdhoulle-org/formation-kibana#1]
Voici les étapes générales pour installer un cluster Elasticsearch de 3 nœuds avec Docker :

1. Installez Docker sur toutes les machines qui seront utilisées pour le cluster.

2. Créez un réseau Docker pour le cluster Elasticsearch :
```
docker network create es_network
```

3. Créez un fichier de configuration `docker-compose.yml` qui spécifie les services pour chaque nœud Elasticsearch. Voici un exemple de configuration :
```
version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es_network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es_network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es_network
volumes:
  es_data:
networks:
  es_network:
```

4. Démarrez les services avec Docker Compose :
```
docker-compose up -d
```

5. Vérifiez que le cluster est en cours d'exécution en exécutant une requête HTTP GET sur l'un des nœuds :
```
curl -X GET "localhost:9200/_cat/nodes?v&pretty"
```

Ces étapes devraient vous permettre de mettre en place un cluster Elasticsearch de 3 nœuds fonctionnel avec Docker. N'oubliez pas de consulter la documentation officielle pour plus d'informations sur la configuration et la personnalisation de votre cluster Elasticsearch.
